LIBS = ../../libzcc_coroutine.a ../../libzcc.a -ldl
iopipe_LIB= ../../libzcc_coroutine.a
LIB_iopipe= -ldl -lssl -lcrypto
LIB_gethostbyname= -lcrypto -lssl -lspf2
LIB_echo_server= -lssl -lcrypto
udcd_client_LIB= ../../libzcc_coroutine.a
LIB_udcd_client= -lssl -lcrypto -ldl -static
udcd_server_LIB= ../../libzcc_coroutine.a
LIB_udcd_server= -lssl -lcrypto -ldl -static
include ../../makefiles/sample.makefile
